site_name: Checkers
site_url: https://www.getcheckers.com/docs/

theme:
  name: material
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - content.action.edit
    - toc.integrate # check feedback

extra:
  version:
    provider: mike

plugins:
  - mkdocstrings

markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      toc_depth: 3
      permalink: "#"

  # all for code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details # allow collapsible blocks
  - admonition # allow call outs

repo_url: https://github.com/checkers-dev/checkers
repo_name: checkers-dev/checkers
edit_uri: edit/main/docs/

# Note: if re-organizing these links, the test_docs.py tests may have to be updated
# as they parse this structure.
nav:
  - Home: index.md
  - Builtin Checks:
    - Model descriptions: checks/check_model_has_description.md
  - Configuration: configuration.md
  - Reference: reference.md
